### ISSUE TITLE
 jsonproperties in Keycloak.Net.Models.ProtocolMappers.ProtocolMapper

### ISSUE THREAD

**Issue by Trapian77** [AnderssonPeter/Keycloak.Net#2]
When using CreateProtocolMapperAsync. You have to define Keycloak.Net.Models.ProtocolMappers.ProtocolMapper with Keycloak.Net.Models.ProtocolMappers.Config which also has the wrong jsonproperties:  [JsonProperty("jsonTypelabel")].

Should the attributes corrected or also a switsch to Dictionary<string,string>.

I could prepare the changes.

**Comment by AnderssonPeter** [comment]
If you create a pull request I would be happy to merge and create a new nuget!
